export enum EngineEvents {
  RespondToGetMatchTeams = 'RespondToGetMatchTeams',
  RespondToCreateTeam = 'RespondToCreateTeam',
  RespondToEnterOnTeam = 'RespondToEnterOnTeam',
  RespondToSelectTeamRole = 'RespondToSelectTeamRole',
  NoticeThatThrownExceptionError = 'NoticeThatThrownExceptionError',
  NoticeThatIsWaitingTeamsReady = 'NoticeThatIsWaitingTeamsReady',
  NoticeThatTeamIsReady = 'NoticeThatTeamIsReady',
  NoticeThatMatchCanStart = 'NoticeThatMatchCanStart',
  NoticeThatMatchStart = 'NoticeThatMatchStart',
  NoticeTeamTurn = 'NoticeTeamTurn',
  NoticeThatPlayerIsAttacking = 'NoticeThatPlayerIsAttacking',
  NoticePlayerAttackResult = 'NoticePlayerAttackResult',
  NoticeThatPlayerIsDefending = 'NoticeThatPlayerIsDefending',
  NoticePlayerDefenceResult = 'NoticePlayerDefenceResult',
  NoticeTurnResult = 'NoticeTurnResult',
  NoticeThatTeamsLost = 'NoticeThatTeamsLost',
  NoticeThatMatchWasCancelled = 'NoticeThatMatchWasCancelled',
  NoticeThatPlayerGaveUp = 'NoticeThatPlayerGaveUp',
  NoticeThatTeamsWon = 'NoticeThatTeamsWon',
}